### ISSUE TITLE
Add project: 0 A.D.

### ISSUE THREAD

**Issue by abrudz** [mahmoud/zerover#86] opened 2021-08-12 16:14 UTC
## Basic info

**Project name**: 0 A.D.
**Project link**: https://play0ad.com/

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

In development since 2001, FOSS since 2009, and yet only on version 0.0.25!

Oh, and the name is very fitting, no?

## Additional notability info

Has Wikipedia page: https://en.wikipedia.org/wiki/0_A.D._(video_game)

## Citation info

---

**Comment by MattTheCuber** [comment] 2024-12-22 20:28
Duplicate of #83?

**Comment by mahmoud** [comment] 2024-12-23 16:58
> Duplicate of #83?

True! Thanks. We gotta get this one 0nboarded. It's great!

**Closed by mahmoud** 2024-12-23 16:58 UTC

**Comment by MattTheCuber** [comment] 2024-12-23 20:59
@mahmoud you can close #83 too.
